version: "3.9"

services:
  db_ice:
    image: postgres:15
    container_name: postgres_b
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data_ice:/var/lib/postgresql/data
    networks:
      - red_proyecto_ice

  app_ice:
    build: .
    container_name: fastapi_b
    restart: always
    depends_on:
      - db_ice
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_ice:5432/${POSTGRES_DB}
    ports:
      - "9010:9010"  # Diferente puerto que app_a
    networks:
      - red_proyecto_ice

volumes:
  pg_data_ice:
    driver: local

networks:
  red_proyecto_ice:
    driver: bridge
