services:
  - type: web
    name: ice-productividad
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PORT
        value: 8000